name: pull_request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  publish:
    uses: batatinha-delivery/workflows/.github/workflows/npm_lint.yml@master
