name: pull_requests

on:
  pull_request:
    branches:
      - main

  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  static_analysis:
    uses: batatinha-delivery/workflows/.github/workflows/npm_check.yml@master
  security:
    uses: batatinha-delivery/workflows/.github/workflows/npm_security.yml@master
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
