name: release

on:
  push:
    branches:
      - main
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  publish:
    uses: batatinha-delivery/workflows/.github/workflows/npm_publish.yml@master
    secrets:
      PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
      NPM_DEPLOY_TOKEN: ${{ secrets.NPM_DEPLOY_TOKEN }}
  documentation:
    uses: batatinha-delivery/workflows/.github/workflows/documentation_publish.yml@master
    secrets:
      GH_PAGES_DEPLOY: ${{ secrets.GH_PAGES_DEPLOY }}
