name: release

on:
  pull_request:
    branches:
      - main
    types: [closed]

  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  publish:
    needs: sec
    uses: batatinha-delivery/workflows/.github/workflows/npm_publish.yml@master
    secrets:
      NPM_DEPLOY_TOKEN: ${{ secrets.NPM_DEPLOY_TOKEN }}
